version: '3.7'

services:
  app:
    image: node:alpine
    command: sh -c "npm install && npm run dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: node_docker
  mysql:
    image: mysql:latest
    volumes:
      - node-docker-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: node_docker
    ports:
      - 3306:3306

volumes:
  node-docker-mysql-data:
      